server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://192.168.56.11:5000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /videos/ {
        proxy_pass http://192.168.56.12:9000/videos-bucket/;
    }

    location / {
        try_files $uri /index.html;
    }
}